<?xml version="1.0"?>
<robot name="ensenso_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

<material name="Ensenso/Blue">
  <color rgba="0.1 0.1 1.0 1.0"/>
</material>

<material name="Ensenso/Black">
  <color rgba="0.0 0.0 0.0 1.0"/>
</material>

  <xacro:macro name="ensenso_N_Series" params="camera parent *origin margin">

    <joint name="${parent}_${camera}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${camera}_mounting_frame" />
    </joint>

    <link name="${camera}_mounting_frame">
      <visual>
        <origin rpy="0 0 0" xyz="0.00 0.0 0.0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/N30-602-16.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="-0.0085 0.00 0.026"/>
        <geometry>
          <box size="${margin+0.192} ${margin+0.050} ${margin+0.052}"/>
        </geometry>
      </collision>
    </link>

    <!-- Projector -->
    <joint name="${camera}_projector_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_projector_lens_frame"/>
      <origin xyz="0 0.00 0.05" rpy=" 0 0 0"/>
    </joint>
    <link name="${camera}_projector_lens_frame"/>

    <!-- Left lens -->
    <joint name="${camera}_left_lense_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_left_lens_frame"/>
      <origin xyz="-0.05 0.00 0.05" rpy=" 0 0 0"/>
    </joint>
    <link name="${camera}_left_lens_frame"/>

    <!-- Right lens -->
    <joint name="${camera}_right_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_right_lens_frame"/>
      <origin xyz="0.05 0.00 0.05" rpy=" 0 0 0"/>
    </joint>
    <link name="${camera}_right_lens_frame"/>

  </xacro:macro>


  <xacro:macro name="ensenso_X200_Series" params="camera parent *origin margin radius_lens_sensor length_lens_sensor radius_lens_projector length_lens_projector">

    <joint name="${parent}_${camera}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${camera}_mounting_frame" />
    </joint>

    <link name="${camera}_mounting_frame">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-5CP-200.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0005 0.033"/>
        <geometry>
          <box size="${margin+0.24350} ${margin+0.08} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${camera}_left_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_left_lens_frame"/>
      <origin xyz="-0.1067 0.036 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="left" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Right lens -->
    <joint name="${camera}_right_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_right_lens_frame"/>
      <origin xyz="0.1067 0.036 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="right" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Projector lens -->
    <joint name="${camera}_projector_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_projector_lens_frame"/>
      <origin xyz="0 0.04 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="projector" radius="${radius_lens_projector}" length_tube="${length_lens_projector}"/>
  </xacro:macro>


  <xacro:macro name="ensenso_X400_Series" params="camera parent *origin margin radius_lens_sensor length_lens_sensor radius_lens_projector length_lens_projector">

    <joint name="${parent}_${camera}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${camera}_mounting_frame" />
    </joint>

    <link name="${camera}_mounting_frame">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-5CP-400.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0005 0.033"/>
        <geometry>
          <box size="${margin+0.4515} ${margin+0.08} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${camera}_left_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_left_lens_frame"/>
      <origin xyz="-0.2109 0.036 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="left" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Right lens -->
    <joint name="${camera}_right_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_right_lens_frame"/>
      <origin xyz="0.2109 0.036 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="right" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Projector lens -->
    <joint name="${camera}_projector_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_projector_lens_frame"/>
      <origin xyz="0 0.04 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="projector" radius="${radius_lens_projector}" length_tube="${length_lens_projector}"/>
  </xacro:macro>


  <xacro:macro name="ensenso_X200_xFA_Series" params="camera parent *origin margin radius_lens_sensor length_lens_sensor radius_lens_projector length_lens_projector">

    <joint name="${parent}_${camera}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${camera}_mounting_frame" />
    </joint>

    <link name="${camera}_mounting_frame">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-xFA-200.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 -0.004 0.033"/>
        <geometry>
          <box size="${margin+0.2870} ${margin+0.09} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${camera}_left_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_left_lens_frame"/>
      <origin xyz="-0.117 0.031 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="left" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Right lens -->
    <joint name="${camera}_right_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_right_lens_frame"/>
      <origin xyz="0.117 0.031 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="right" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Projector lens -->
    <joint name="${camera}_projector_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_projector_lens_frame"/>
      <origin xyz="0 0.041 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="projector" radius="${radius_lens_projector}" length_tube="${length_lens_projector}"/>
  </xacro:macro>


  <xacro:macro name="ensenso_X400_xFA_Series" params="camera parent *origin margin radius_lens_sensor length_lens_sensor radius_lens_projector length_lens_projector">

    <joint name="${parent}_${camera}_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}" />
      <child link="${camera}_mounting_frame" />
    </joint>

    <link name="${camera}_mounting_frame">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-xFA-400.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 -0.004 0.033"/>
        <geometry>
          <box size="${margin+0.4950} ${margin+0.09} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${camera}_left_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_left_lens_frame"/>
      <origin xyz="-0.22125 0.031 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="left" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Right lens -->
    <joint name="${camera}_right_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_right_lens_frame"/>
      <origin xyz="0.22125 0.031 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="right" radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}"/>

    <!-- Projector lens -->
    <joint name="${camera}_projector_lens_joint" type="fixed">
      <parent link="${camera}_mounting_frame"/>
      <child link="${camera}_projector_lens_frame"/>
      <origin xyz="0 0.041 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <xacro:objective camera="${camera}" margin="${margin}" name="projector" radius="${radius_lens_projector}" length_tube="${length_lens_projector}"/>
  </xacro:macro>


  <xacro:macro name="objective" params="camera margin name radius length_tube">
    <link name="${camera}_${name}_lens_frame">
      <visual>
        <origin xyz="0.0 0.0 ${length_tube / 2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length_tube}" radius="${radius}"/>
        </geometry>
        <material name="Ensenso/Black"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${(length_tube+2*margin) / 2.0}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length_tube+2*margin}" radius="${radius+margin}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

</robot>